defaults:
  # - data: 2023-03-13-video-game-classification.yaml
  # - data: 2023-03-13-content-type-classification.yaml
  - data: 2023-04-05-hierarchy-dataset-v01.yaml
  - model: mobilenetv3.yaml
  - optimizer: adam.yaml
  - criterion: bce.yaml
  - metrics: image-classification.yaml
  - callbacks: default.yaml
  - trainer: default.yaml
  - paths: default.yaml
  - hydra: default.yaml
  - experiment: null
  - _self_

task_name: 'image-classification'
task_type: test
img_size: [224, 224]
