_target_: diploma.models.mobilenetv3.MobileNetV3Module
model: 
  _target_: diploma.models.components.mobilenetv3_simple_softmax.MobileNetV3
  num_classes: 11
  categories_json: /media/ap/Transcend/Projects/diploma/_local/diploma/assets/data/tmp/openimages/categories.json
metrics: ${metrics}
criterion: ${criterion}
categories_json: /media/ap/Transcend/Projects/diploma/_local/diploma/assets/data/tmp/openimages/categories.json