_target_: diploma.models.mobilenetv3.MobileNetV3Module
model: 
  _target_: diploma.models.components.mobilenetv3_simple_sigmoid.MobileNetV3
  num_classes: 17
  hierarchy_json: /media/ap/Transcend/Projects/diploma/_local/diploma/assets/data/tmp/openimages/hierarchy.json
metrics: ${metrics}
criterion: ${criterion}
categories_json: /media/ap/Transcend/Projects/diploma/_local/diploma/assets/data/tmp/openimages/categories.json