_target_: lightning.pytorch.Trainer
accelerator: gpu
max_epochs: 1000
log_every_n_steps: 1
check_val_every_n_epoch: 1
logger:
  - _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
    save_dir: ${hydra:runtime.output_dir}
  - _target_: lightning.pytorch.loggers.CSVLogger
    save_dir: ${hydra:runtime.output_dir}